name:                SSBX16
version:             1.0.0.0
homepage:            http://www.prg.nii.ac.jp/project/bigul/
bug-reports:         https://bitbucket.org/prl_tokyo/bigul/issues
license:             PublicDomain
author:              Josh Ko, Tao Zan, Li Liu, Zirun Zhu, Jorge Mendes, and Zhenjiang Hu
maintainer:          Josh Ko <hsiang-shang@nii.ac.jp> and Zirun Zhu <zhu@nii.ac.jp>
category:            Language, Generics, Lenses
build-type:          Simple
cabal-version:       1.22

library
  exposed-modules:     Alignment
                       Basic
                       BiYacc
                       Brul
                       List

  if impl(ghc >= 7.10) && impl(ghc < 8)
    build-depends:     base == 4.8.*,
                       mtl >= 2.2 && < 2.3,
                       containers >= 0.5,
                       template-haskell >= 2.10 && < 2.11,
                       parsec >= 3.1 && < 3.2,
                       BiGUL >= 1.0.0
  else
  if impl(ghc <= 8.4.4) && impl (ghc >= 8)
    build-depends:     base >= 4.9 && < 4.12,
                       mtl >= 2.2 && < 2.3,
                       containers >= 0.5,
                       template-haskell >= 2.11,
                       parsec >= 3.1 && < 3.2,
                       BiGUL >= 1.0.0
  else
  if impl(ghc <= 8.6.5) && impl (ghc > 8.4.4)
    build-depends:     base >= 4.12 && < 4.14,
                       mtl >= 2.2 && < 2.3,
                       containers >= 0.5 && < 0.7,
                       template-haskell >= 2.11 && < 2.15,
                       parsec >= 3.1 && < 3.2,
                       BiGUL >= 1.0.0
  else
  if impl(ghc <= 8.8.4) && impl (ghc > 8.6.5)
    build-depends:      base >= 4.12 && < 4.14,
                        mtl >= 2.2 && < 2.3,
                        containers >= 0.5 && < 0.7,
                        template-haskell >= 2.15 && < 2.16,
                        parsec >= 3.1 && < 3.2,
                        BiGUL >= 1.0.0
  else
  if impl(ghc <= 8.10.7) && impl (ghc > 8.8.4)
    build-depends:      base >= 4.14 && < 4.15,
                        mtl >= 2.2 && < 2.3,
                        containers >= 0.5 && < 0.7,
                        template-haskell >= 2.16 && < 2.17,
                        parsec >= 3.1 && < 3.2,
                        BiGUL >= 1.0.0
  else
  if impl(ghc <= 9.0.2) && impl (ghc > 8.10.7)
    build-depends:      base >= 4.15 && < 4.16,
                        mtl >= 2.2 && < 2.3,
                        containers >= 0.5 && < 0.7,
                        template-haskell >= 2.17 && < 2.18,
                        parsec >= 3.1 && < 3.2,
                        BiGUL >= 1.0.0
  else
  if impl(ghc <= 9.2.8) && impl (ghc > 9.0.2)
    build-depends:      base >= 4.16 && < 4.17,
                        mtl >= 2.2 && < 2.3,
                        containers >= 0.5 && < 0.7,
                        template-haskell >= 2.18 && < 2.19,
                        parsec >= 3.1 && < 3.2,
                        BiGUL >= 1.0.0
  else
  if impl(ghc <= 9.4.8) && impl (ghc > 9.2.8)
    build-depends:      base >= 4.17 && < 4.18,
                        mtl >= 2.2 && < 2.3,
                        containers >= 0.5 && < 0.7,
                        template-haskell >= 2.19 && < 2.20,
                        parsec >= 3.1 && < 3.2,
                        BiGUL >= 1.0.0
  else
  if impl(ghc <= 9.6.7) && impl (ghc > 9.4.8)
    build-depends:      base >= 4.18 && < 4.19,
                        mtl >= 2.3 && < 2.4,
                        containers >= 0.5 && < 0.7,
                        template-haskell >= 2.20 && < 2.21,
                        parsec >= 3.1 && < 3.2,
                        BiGUL >= 1.0.0
  else
  if impl(ghc <= 9.8.4) && impl (ghc > 9.6.7)
    build-depends:      base >= 4.19 && < 4.20,
                        mtl >= 2.3 && < 2.4,
                        containers >= 0.5 && < 0.7,
                        template-haskell >= 2.21 && < 2.22,
                        parsec >= 3.1 && < 3.2,
                        BiGUL >= 1.0.0
  default-language:    Haskell2010
